language: python

dist: xenial

before_install:
    - sudo apt-get -y install texlive-xetex dvipng

matrix:
    include:
        - name: "Python 3.8"
          python: 3.8

install:
    - source .build_tools/travis/install.sh

script:
    - bash .build_tools/travis/test_script.sh

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs/_build/html # Folder containing the compiled HTML
    on:
        branch: master

